version: '3.7'
services:
  eventbus:
    image: brewblox/mosquitto:develop
    ports:
      - "1883:1883"
  tilt:
    # Manually build the "local" image before use
    image: brewblox/brewblox-tilt:local
    privileged: true
    network_mode: host
    command: --mqtt-protocol=mqtt --debug
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./
        target: /app
      - type: bind
        source: ./share
        target: /share
