version: "3.7"
services:
  eventbus:
    image: ghcr.io/brewblox/mosquitto:develop
    ports:
      - "1883:1883"
  tilt:
    # Manually build the "local" image before use
    image: ghcr.io/brewblox/brewblox-tilt:local
    privileged: true
    command: --debug
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./brewblox_tilt
        target: /app/brewblox_tilt
      - type: bind
        source: ./share
        target: /share
      - type: bind
        source: /var/run/dbus
        target: /var/run/dbus
