[tool.poetry]
name = "brewblox-tilt"
version = "2.1.0"
description = "Tilt hydrometer service for BrewBlox"
authors = ["James Sandford <brewblox-tilt@j616s.co.uk>"]
license = "GPL-3.0"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.7,<4"
brewblox-service = "^0.32.2"
numpy = "^1.18.2"
Pint = "^0.17"

[tool.poetry.dev-dependencies]
pytest-flake8 = "^1.0.7"
pytest-cov = "^2.11.1"
pytest-mock = "^3.5.1"
pytest-aiohttp = "^0.3.0"
flake8 = "^3.8.4"
autopep8 = "^1.5.5"
flake8-quotes = "^3.2.0"
asyncmock = "^0.4.2"
click = "^7.1.2"
PyYAML = "^5.4.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
