[tool.poetry]
name = "brewblox-tilt"
version = "2.1.0"
description = "Tilt hydrometer service for Brewblox"
authors = ["BrewPi <development@brewpi.com>", "James Sandford <brewblox-tilt@j616s.co.uk>"]
license = "GPL-3.0"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<4"
brewblox-service = "^0.33.0"
numpy = "^1.18.2"
Pint = "^0.17"
PyBluez = "0.22"
beacontools = "^2.1.0"
"ruamel.yaml" = "^0.17.17"

[tool.poetry.dev-dependencies]
pytest-flake8 = "^1.0.7"
pytest-cov = "^2.12.1"
pytest-mock = "^3.6.1"
pytest-aiohttp = "^0.3.0"
flake8 = "^3.9.2"
autopep8 = "^1.5.7"
flake8-quotes = "^3.2.0"
click = "^8.0.1"
PyYAML = "^5.4.1"
pytest = "^6.2.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
