[tool.poetry]
name = "brewblox-tilt"
version = "2.1.0"
description = "Tilt hydrometer service for Brewblox"
authors = ["BrewPi <development@brewpi.com>", "James Sandford <brewblox-tilt@j616s.co.uk>"]
license = "GPL-3.0"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.7,<4"
brewblox-service = "^0.32.3"
numpy = "^1.18.2"
Pint = "^0.17"
PyBluez = "0.22"

[tool.poetry.dev-dependencies]
pytest-flake8 = "^1.0.7"
pytest-cov = "^2.11.1"
pytest-mock = "^3.6.1"
pytest-aiohttp = "^0.3.0"
flake8 = "^3.9.2"
autopep8 = "^1.5.7"
flake8-quotes = "^3.2.0"
asyncmock = "^0.4.2"
click = "^7.1.2"
PyYAML = "^5.4.1"
pytest = "^6.2.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
